Controllers/ExchangeController.cs
using CheeryAssessment.Attributes;
using CheeryAssessment.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace CheeryAssessment.Controllers
{
    [SessionAuthorize]
    public class ExchangeController : Controller
    {
        private DB_Entities _db = new DB_Entities();

        // GET: Exchange
        public ActionResult Index()
        {
            ExchangeIndexModel indexModel = new ExchangeIndexModel();
            indexModel.exchangeRateModel = GetRate();
            indexModel.userBalanceModel = GetBalance();
            indexModel.exchangeLogModel = new ExchangeLogModel
            {
                avail_currency_code = new[]
                {
                    new SelectListItem{ Value = indexModel.exchangeRateModel.rates.MYR.ToString() , Text = "MYR", Selected = true },
                    new SelectListItem{ Value = indexModel.exchangeRateModel.rates.AUD.ToString() , Text = "AUD" },
                    new SelectListItem{ Value = indexModel.exchangeRateModel.rates.SGD.ToString() , Text = "SGD" }
                }
            };
            

            //ViewBag.RateList = ConversionRateSelectList(indexModel.exchangeRateModel, true);
            //ViewData["RateList"] = ConversionRateSelectList(indexModel.exchangeRateModel, true);

            //ViewBag.CurrencyCode = ConversionRateSelectList(indexModel.exchangeRateModel, false);

            return View(indexModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ExchangeIndexModel indexModel, FormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                DateTime dtNow = DateTime.Now;
                long userid = long.Parse(Session["userid"].ToString());

                indexModel.exchangeLogModel.user_id = userid;
                indexModel.exchangeLogModel.transaction_date = dtNow;
                indexModel.exchangeLogModel.to_currency_code = formCollection["ToCurrencyCode"];

                
                var dataUserBalance = _db.userBalanceModels.Where(b => b.user_id == userid).ToList();

                if (dataUserBalance.Count > 0)
                {
                    decimal toAmount = decimal.Parse(indexModel.exchangeLogModel.to_amount);
                    decimal fromAmount = decimal.Parse(indexModel.exchangeLogModel.from_amount);
                    decimal balanceUSD = decimal.Parse(dataUserBalance.FirstOrDefault().bal_usd.ToString());
                    balanceUSD = decimal.Subtract(balanceUSD, fromAmount);

                    dataUserBalance.FirstOrDefault().bal_usd = balanceUSD.ToString();
                    dataUserBalance.FirstOrDefault().last_update_date = dtNow;

                    switch (indexModel.exchangeLogModel.to_currency_code)
                    {
                        case "MYR":
                            decimal balanceMYR = decimal.Parse(dataUserBalance.FirstOrDefault().bal_myr.ToString());
                            balanceMYR = decimal.Add(balanceMYR, toAmount);
                            dataUserBalance.FirstOrDefault().bal_myr = balanceMYR.ToString();
                            break;
                        case "AUD":
                            decimal balanceAUD = decimal.Parse(dataUserBalance.FirstOrDefault().bal_aud.ToString());
                            balanceAUD = decimal.Add(balanceAUD, toAmount);
                            dataUserBalance.FirstOrDefault().bal_aud = balanceAUD.ToString();
                            break;
                        case "SGD":
                            decimal balanceSGD = decimal.Parse(dataUserBalance.FirstOrDefault().bal_sgd.ToString());
                            balanceSGD = decimal.Add(balanceSGD, toAmount);
                            dataUserBalance.FirstOrDefault().bal_sgd = balanceSGD.ToString();
                            break;
                    }

                }


                //var data = _db.userModels.Where(s => s.email.Equals(email) && s.password.Equals(f_password)).ToList();

                _db.Configuration.ValidateOnSaveEnabled = false;
                _db.exchangeLogModels.Add(indexModel.exchangeLogModel);
                _db.SaveChanges();
            }
            else
            {
                ViewBag.error = "Login failed";
                //return RedirectToAction("Login");
                return View();
            }

            //return View();
            return RedirectToAction("ViewReport");
        }

        public ExchangeRateModel GetRate()
        {
            HttpWebRequest webreq = (HttpWebRequest)WebRequest.Create("https://openexchangerates.org/api/latest.json?app_id=43207fc5dc7148ae836473bbb1815996");
            webreq.Method = "GET";
            string responseFromServer = "";

            WebResponse response = webreq.GetResponse();
            using (var dataStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(dataStream);
                responseFromServer = reader.ReadToEnd();
                Console.WriteLine(responseFromServer);
            }
            response.Close();

            var result = new JsonResult
            {
                Data = JsonConvert.DeserializeObject(responseFromServer)
            };

            ExchangeRateModel exchangeRateModel = new JavaScriptSerializer().Deserialize<ExchangeRateModel>(result.Data.ToString());



            return exchangeRateModel;
        }


        public UserBalanceModel GetBalance()
        {
            long userid = long.Parse(Session["userid"].ToString());
            var data = _db.userBalanceModels.Where(u => u.user_id == userid).ToList();
            UserBalanceModel res = data.FirstOrDefault();

            return res;
        }



        [NonAction]
        public SelectList ConversionRateSelectList(ExchangeRateModel _rateModel, bool isGetRate)
        {
            List<SelectListItem> list = new List<SelectListItem>();

            list.Add(new SelectListItem()
            {
                Text = "MYR",
                Value = ((isGetRate == true) ? _rateModel.rates.MYR.ToString() : "MYR")
            });

            list.Add(new SelectListItem()
            {
                Text = "AUD",
                Value = ((isGetRate == true) ? _rateModel.rates.AUD.ToString() : "AUD")
            });

            list.Add(new SelectListItem()
            {
                Text = "SGD",
                Value = ((isGetRate == true) ? _rateModel.rates.SGD.ToString() : "SGD")
            });

            return new SelectList(list, "Value", "Text");
        }


        public ActionResult ViewReport()
        {
            long userid = long.Parse(Session["userid"].ToString());

            var data = _db.exchangeLogModels
                .Where(b => b.user_id == userid)
                .OrderByDescending(b => b.id)
                .ToList();

            List<ExchangeLogModel> listExchangeLogModel = data;

            return View(listExchangeLogModel);
        }
    }
}

Views/Exchange/Index.cshtml
@model CheeryAssessment.Models.ExchangeIndexModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Exchange</h2>

<script src="~/Scripts/jquery-3.4.1.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var selectedText = $("#ddlRateList").find("option:selected").text();
        var selectedValue = $("#ddlRateList").val();

        updateRemarkLabel();
        updateToAmount();
        HiddenToCurrencyCode();


        $("#ddlRateList").change(function () {
            selectedText = $("#ddlRateList").find("option:selected").text();
            selectedValue = $("#ddlRateList").val();

            updateRemarkLabel();
            HiddenToCurrencyCode();

            $("#fromAmount").val("");
            $("#toAmount").val("");
        });

        $("#fromAmount").keyup(function () {
            updateToAmount();
        });



        function updateRemarkLabel() {
            //alert("Selected Text: " + selectedText + " Value: " + selectedValue);
            var tempRemark = "*1 USD = " + selectedValue + " " + selectedText;
            $("#spanRemark").text(tempRemark);

            $("#conversion_rate").val(selectedValue);
        }

        function HiddenToCurrencyCode() {
            $("#hdnToCurrencycode").val($("#ddlRateList").find("option:selected").text());
        }

        function updateToAmount() {
            var vFromAmount = $("#fromAmount").val();
            var divider = 100000000000000000000000000000;
            var vToAmount = ((vFromAmount * divider) * (selectedValue * divider)) / (divider * divider);
            
            $("#toAmount").val(vToAmount);
        }


        $("#formExchange").submit(function (event) {
            if ($("#fromAmount").val() > @Model.userBalanceModel.bal_usd) {
                alert("Exchange amount cannot greater than your balance USD " + @Model.userBalanceModel.bal_usd);

                return false;
            }
            else {
                if (confirm('Are you confirm to exchange ?')) {
                    return true
                }
                else {
                    event.preventDefault;
                    return false;
                }
            }
        });
    });
</script>

<br />
<table>
    <tr>
        <td>User ID</td>
        <td>: @Html.DisplayFor(model => model.userBalanceModel.user_id)</td>
    </tr>
    <tr>
        <td>User Name</td>
        <td>&nbsp;: @Html.DisplayFor(model => model.userBalanceModel.UserModel.username)</td>
    </tr>
    <tr>
        <td>Balance (USD)</td>
        <td>&nbsp;: @Html.DisplayFor(model => model.userBalanceModel.bal_usd)</td>
    </tr>
    <tr>
        <td>Balance (MYR)</td>
        <td>&nbsp;: @Html.DisplayFor(model => model.userBalanceModel.bal_myr)</td>
    </tr>
    <tr>
        <td>Balance (AUD)</td>
        <td>&nbsp;: @Html.DisplayFor(model => model.userBalanceModel.bal_aud)</td>
    </tr>
    <tr>
        <td>Balance (SGD)</td>
        <td>&nbsp;: @Html.DisplayFor(model => model.userBalanceModel.bal_sgd)</td>
    </tr>
</table>



<br />
<br />

<table>
    <tr>
        <td width="150px"><b>Currency Code</b></td>
        <td><b>Rate</b></td>
    </tr>
    <tr>
        <td width="150px">MYR</td>
        <td>@Html.DisplayFor(m => m.exchangeRateModel.rates.MYR) </td>
    </tr>
    <tr>
        <td width="150px">AUD</td>
        <td>@Html.DisplayFor(m => m.exchangeRateModel.rates.AUD) </td>
    </tr>
    <tr>
        <td width="150px">SGD</td>
        <td>@Html.DisplayFor(m => m.exchangeRateModel.rates.SGD) </td>
    </tr>
</table>

<br />
<br />

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                @using (Html.BeginForm("Index", "Exchange", FormMethod.Post, new { @id = "formExchange" }))
                {
                    @Html.AntiForgeryToken()

                    @Html.HiddenFor(m => m.exchangeLogModel.from_currency_code, new { Value = "USD" })
                    @Html.HiddenFor(m => m.exchangeLogModel.conversion_rate, new { @id = "conversion_rate" })

                    <table>
                        <tr>
                            <td>
                                @Html.DropDownListFor(m => m.exchangeLogModel.to_currency_code, new SelectList(Model.exchangeLogModel.avail_currency_code, "Value", "Text"), new { @class = "form-control", @id = "ddlRateList", style = "width:80px;" })
                                <input type="hidden" id="hdnToCurrencycode" name="ToCurrencyCode" />
                            </td>
                            <td>
                                &nbsp;&nbsp;&nbsp;
                            </td>
                            <td>
                                @Html.TextBoxFor(m => m.exchangeLogModel.from_amount, "", new { @class = "form-control", @id = "fromAmount", style = "width:200px;", @type = "number" })
                            </td>
                            <td>
                                &nbsp;&nbsp;&nbsp;
                            </td>
                            <td>
                                @Html.TextBoxFor(m => m.exchangeLogModel.to_amount, "", new { @class = "form-control", @id = "toAmount", style = "width:200px;", @readonly = "readonly" })
                            </td>
                        </tr>


                        <tr>
                            <td colspan="3">
                                <span id="spanRemark"></span>
                            </td>
                        </tr>
                    </table>

                    <div class="form-group">
                        @*<input type="submit" name="submit" class="btn btn-primary" value="Submit" />*@
                        <input type="submit" name="submit" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Views/Exchange/ViewReport.cshtml
@model IEnumerable <CheeryAssessment.Models.ExchangeLogModel>

@{
    ViewBag.Title = "ViewReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Transaction History</h2>

<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.transaction_date)*@
            Transaction Date
        </th>
        <th>
            From Currency
        </th>
        <th>
            Amount
        </th>
        <th>
            To Currency
        </th>
        <th>
            Conversion Rate
        </th>
        <th>
            Amount
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.transaction_date)
            </td>
            <td>
                @Html.DisplayFor(model => item.from_currency_code)
            </td>
            <td>
                @Html.DisplayFor(model => item.from_amount)
            </td>
            <td>
                @Html.DisplayFor(model => item.to_currency_code)
            </td>
            <td>
                @Html.DisplayFor(model => item.conversion_rate)
            </td>
            <td>
                @Html.DisplayFor(model => item.to_amount)
            </td>
        </tr>
    }
</table>